# Generated by Django 4.2.2 on 2023-06-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friendleaf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagenUrl',
            field=models.ImageField(upload_to='imgProductos'),
        ),
    ]
